[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.mbstring", "php83Extensions.curl", "php83Extensions.openssl", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "frankenphp run --config /app/Caddyfile"
